# Open notebook in Colab


<a href="https://colab.research.google.com/github/bibofeng/docs/blob/main/agentnet_optimizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Colab Setup
## colab shell setup


In [ ]:
from IPython.display import JSON
from google.colab import output
from subprocess import getoutput
import os

In [ ]:
# run colab bash shell teminal window

def shell(command):
  if command.startswith('cd'):
    path = command.strip().split(maxsplit=1)[1]
    os.chdir(path)
    return JSON([''])
  return JSON([getoutput(command)])
output.register_callback('shell', shell)

In [ ]:
#@title Colab Shell
%%html
<div id=term_demo></div>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/jquery.terminal/css/jquery.terminal.min.css" rel="stylesheet"/>
<script>
  $('#term_demo').terminal(async function(command) {
      if (command !== '') {
          try {
              let res = await google.colab.kernel.invokeFunction('shell', [command])
              let out = res.data['application/json'][0]
              this.echo(new String(out))
          } catch(e) {
              this.error(new String(e));
          }
      } else {
          this.echo('');
      }
  }, {
      greetings: 'Welcome to Colab Shell',
      name: 'colab_demo',
      height: 250,
      prompt: 'colab > '
  });

#@title Colab Shell
%%html
<div id=term_demo></div>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/jquery.terminal/css/jquery.terminal.min.css" rel="stylesheet"/>
<script>
  $('#term_demo').terminal(async function(command) {
      if (command !== '') {
          try {
              let res = await google.colab.kernel.invokeFunction('shell', [command])
              let out = res.data['application/json'][0]
              this.echo(new String(out))
          } catch(e) {
              this.error(new String(e));
          }
      } else {
          this.echo('');
      }
  }, {
      greetings: 'Welcome to Colab Shell',
      name: 'colab_demo',
      height: 250,
      prompt: 'colab > '
  });

## Mount Google Drive

In [ ]:
#mount google drive of GwsArk
# from google.colab import drive
# drive.mount('/content/gdrive')
# cp /content/gdrive/MyDrive/config/* ./

## Upload Config Files From Local Server

In [ ]:
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

## Import configurae credential file


In [ ]:
#import config credential of user name and password
import config
user = config.USER
pw = config.PW
url = config.URL
#install bblib 
!pip install git+http://$user:$pw@$url

## import talab package

In [ ]:
url = 'https://anaconda.org/conda-forge/libta-lib/0.4.0/download/linux-64/libta-lib-0.4.0-h516909a_0.tar.bz2'
!curl -L $url | tar xj -C /usr/lib/x86_64-linux-gnu/ lib --strip-components=1
url = 'https://anaconda.org/conda-forge/ta-lib/0.4.19/download/linux-64/ta-lib-0.4.19-py37ha21ca33_2.tar.bz2'
!curl -L $url | tar xj -C /usr/local/lib/python3.7/dist-packages/ lib/python3.7/site-packages/talib --strip-components=3
import talib

# Setup tensorboard on Notebook

In [ ]:
# Load the TensorBoard notebook extension
%load_ext tensorboard

In [ ]:
#Open tensorboard in notebook: 
%tensorboard --logdir /content/gdrive/MyDrive/logs/test_state_1d/

## Run python scripts 


In [ ]:
!python  /usr/local/lib/python3.7/dist-packages/DRLON/train_drlon_model.py --cuda gpu --data YNDX_160101_161231.csv --valdata YNDX_150101_151231.csv -r test_state_1d


In [3]:
import numpy as np
import pandas as pd


In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
 asset_len = 2  ## Appl google
 ind_len = 3  ## Close , High , Vol, VWap
 window_len = 4
 ## so the imaging should be H=3*2, W=4
 #
 data_len = 5
 npdata = np.zeros((data_len, ind_len * asset_len, window_len))
 npdata

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
# With two column indices with
# one index with other name
data = np.zeros((2,2))
df2 = pd.DataFrame(data, index =['first',
                                 'second'],
                   columns =['a', 'b1'])
df2

a   b1
first   0.0  0.0
second  0.0  0.0

In [8]:
indlist= []
data= np.zeros((3))
for i in range(3):
  x = "ind" + str(i)
  y = np.float32( str(i+1) + "." + ( "0"+str(i+1))[-2:])
  indlist.append(x)
  data[i] = float("{:.4f}".format(y))
  print(indlist[i])
print(data)

ind0
ind1
ind2
[1.01 2.02 3.03]


In [10]:
asset_len = 2
ind_len = 3
data_len = 4
ind_windows = 5
 
data_row= np.zeros((ind_len))
data =np.zeros((data_len *asset_len ,ind_len)) 
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
asset_len = 2
ind_len = 3
data_len = 4
ind_windows =2
data =np.zeros((data_len *asset_len ,ind_len * ind_windows)) 

indlist= []
assetlist= []
rowindex=[]
tickers=[]
tickeridx=[]
for k in range(asset_len):
  tickers.append("ticker"+str(k))


for k in range(asset_len):
  for j in range(data_len):
    rowindex.append(  j)
    tickeridx.append("tkr_"+str(k)+"."+str(j))


for i in range(ind_len):
  for j in range(ind_windows):
    if ind_windows <=1 :
       indlist.append("ind_" + str(i+1) )
    else:
      indlist.append("ind_" + str(i+1) + "." + str(j+1))

print(indlist)
print(tickers)
print(rowindex)
print(tickeridx)

['ind_1.1', 'ind_1.2', 'ind_2.1', 'ind_2.2', 'ind_3.1', 'ind_3.2']
['ticker0', 'ticker1']
[0, 1, 2, 3, 0, 1, 2, 3]
['tkr_0.0', 'tkr_0.1', 'tkr_0.2', 'tkr_0.3', 'tkr_1.0', 'tkr_1.1', 'tkr_1.2', 'tkr_1.3']


In [48]:
len(indlist)

6

In [49]:


print(data)
m = 0
n = 0
i=j=k=0
for k in range(asset_len):
  for j in range(data_len):
    data_row= np.zeros((ind_len))
    m =  k *data_len + j
    for i in range(ind_len):
      for w in range(ind_windows):
        if ind_windows <=1 :
          n = i * ind_windows  
          y = np.float32( str(k+1) + "."  + ( "0"+str(j+1))[-2:] + ( "0"+str(i+1))[-2:] )
        else:
          n = i * ind_windows + w
          y = np.float32( str(k+1) + "."+ ( "0"+str(j+1))[-2:]  + ( "0"+str(i+1))[-2:] + ( "0"+str(w+1))[-2:]  )
        data_row[i] = float("{:.6f}".format(y))
        data[m,n] = float("{:.6f}".format(y))
      #print(data_row[i])
     # print(m)
    #print(data_row)
print(data)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1.010101 1.010102 1.010201 1.010202 1.010301 1.010302]
 [1.020101 1.020102 1.020201 1.020202 1.020301 1.020302]
 [1.030101 1.030102 1.030201 1.030202 1.030301 1.030302]
 [1.040101 1.040102 1.040201 1.040202 1.040301 1.040302]
 [2.010101 2.010102 2.010201 2.010202 2.010301 2.010302]
 [2.020101 2.020102 2.020201 2.020202 2.020301 2.020302]
 [2.030101 2.030102 2.030201 2.030202 2.030301 2.030302]
 [2.040101 2.040102 2.040201 2.040202 2.040301 2.040302]]


In [136]:
type(data)

numpy.ndarray

In [50]:
df_data = pd.DataFrame(np.array(data), index =tickeridx, columns =indlist)
df_data

ind_1.1   ind_1.2   ind_2.1   ind_2.2   ind_3.1   ind_3.2
tkr_0.0  1.010101  1.010102  1.010201  1.010202  1.010301  1.010302
tkr_0.1  1.020101  1.020102  1.020201  1.020202  1.020301  1.020302
tkr_0.2  1.030101  1.030102  1.030201  1.030202  1.030301  1.030302
tkr_0.3  1.040101  1.040102  1.040201  1.040202  1.040301  1.040302
tkr_1.0  2.010101  2.010102  2.010201  2.010202  2.010301  2.010302
tkr_1.1  2.020101  2.020102  2.020201  2.020202  2.020301  2.020302
tkr_1.2  2.030101  2.030102  2.030201  2.030202  2.030301  2.030302
tkr_1.3  2.040101  2.040102  2.040201  2.040202  2.040301  2.040302

In [103]:
df1 = pd.DataFrame(
     {
         "A": ["A0", "A1", "A2", "A3"],
         "B": ["B0", "B1", "B2", "B3"],
         "C": ["C0", "C1", "C2", "C3"],
         "D": ["D0", "D1", "D2", "D3"],
     },
     index=[0, 1, 2, 3],
 )
 

df2 = pd.DataFrame(
     {
         "A": ["A4", "A5", "A6", "A7"],
         "B": ["B4", "B5", "B6", "B7"],
         "C": ["C4", "C5", "C6", "C7"],
         "D": ["D4", "D5", "D6", "D7"],
     },
     index=[0, 1, 2, 3],
 )
 

df3 = pd.DataFrame(
     {
         "A": ["A8", "A9", "A10", "A11"],
         "B": ["B8", "B9", "B10", "B11"],
         "C": ["C8", "C9", "C10", "C11"],
         "D": ["D8", "D9", "D10", "D11"],
     },
       index=[0, 1, 2, 3],
 )
 

frames = [df1, df2, df3]

result = pd.concat(frames)

In [29]:
result

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [37]:
df0 = pd.concat([df1,df2])

In [38]:
pd.concat([df0,df3])

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [30]:
result = pd.concat(frames, keys=["x", "y", "z"])

In [31]:
result

A    B    C    D
x 0   A0   B0   C0   D0
  1   A1   B1   C1   D1
  2   A2   B2   C2   D2
  3   A3   B3   C3   D3
y 0   A4   B4   C4   D4
  1   A5   B5   C5   D5
  2   A6   B6   C6   D6
  3   A7   B7   C7   D7
z 0   A8   B8   C8   D8
  1   A9   B9   C9   D9
  2  A10  B10  C10  D10
  3  A11  B11  C11  D11

In [23]:
result.to_xarray()

<xarray.Dataset>
Dimensions:  (level_0: 3, level_1: 12)
Coordinates:
  * level_0  (level_0) object 'x' 'y' 'z'
  * level_1  (level_1) int64 0 1 2 3 4 5 6 7 8 9 10 11
Data variables:
    A        (level_0, level_1) object 'A0' 'A1' 'A2' 'A3' ... 'A9' 'A10' 'A11'
    B        (level_0, level_1) object 'B0' 'B1' 'B2' 'B3' ... 'B9' 'B10' 'B11'
    C        (level_0, level_1) object 'C0' 'C1' 'C2' 'C3' ... 'C9' 'C10' 'C11'
    D        (level_0, level_1) object 'D0' 'D1' 'D2' 'D3' ... 'D9' 'D10' 'D11'

In [24]:
result

A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11